### ISSUE TITLE
Maven repo

### ISSUE THREAD

**Issue by carlosmonterocanabal** [xfyre/tapestry5-xtensions#3]
Hi,
I have found this great lib. I would like to know if you will upload to some maven repo??
Regards

**Comment by xfyre** [comment]
Yes, that would be a good idea. Could you suggest any repository?

**Comment by carlosmonterocanabal** [comment]
You can use Sonatype (http://central.sonatype.org/pages/ossrh-guide.html). You have to create two jira request and some work more, but then your lib will be available on maven central.
Also, I have my own Maven Artifactory Repository (http://artifactory.carlosmontero.es), if you want I can upload it on my repo on a public repository (libs-release-local or libs-snapshot-local).

**Comment by xfyre** [comment]
https://issues.sonatype.org/browse/OSSRH-22107 filed

On Wed, Apr 20, 2016 at 11:22 AM, carlosmonterocanabal <
notifications@github.com> wrote:

> You can use Sonatype (http://central.sonatype.org/pages/ossrh-guide.html).
> You have to create two jira request and some work more, but then your lib
> will be available on maven central.
> Also, I have my own Maven Artifactory Repository (
> http://artifactory.carlosmontero.es), if you want I can upload it on my
> repo on a public repository (libs-release-local or libs-snapshot-local).
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/xfyre/tapestry5-xtensions/issues/3#issuecomment-212321138

## 

Ilya Obshadko

**Comment by xfyre** [comment]
Version 0.92-RELEASE released to Sonatype

**Comment by carlosmonterocanabal** [comment]
Great work!
